docs/DeveloperGuide.md
Update the following with more relevant information: 
- user profiles
- value propositions 
- user stories regarding finding/viewing
- use case 
- NFR 
- glossary
=> Add Search feature to DeveloperGuide.md

README.md, docs/DeveloperGuide.md
Update the following with more relevant information:
DeveloperGuide.md:
user profiles
use case
ReadMe.md:
remove traces of AB3
update link to reflect WardWatch
=> Add Delete feature to DeveloperGuide.md

docs/DeveloperGuide.md, docs/UserGuide.md, docs/index.md
This PR will:
1) Edit names from AB-3 to WardWatch sitewide.
2) Under Developer's Guide, will require inclusion of information to:
- User stories
- Use cases
- NFRs
- Glossary
Closes #40
=> Update website to fit WardWatch theme, and update DG

docs/DeveloperGuide.md
Added User Case for List function
=> Add User Case for List function

src/main/java/seedu/address/logic/Messages.java, src/main/java/seedu/address/logic/commands/EditCommand.java, src/main/java/seedu/address/logic/parser/AddCommandParser.java, src/main/java/seedu/address/logic/parser/CliSyntax.java, src/main/java/seedu/address/logic/parser/EditCommandParser.java, src/main/java/seedu/address/logic/parser/ParserUtil.java, src/main/java/seedu/address/model/person/Diagnosis.java, src/main/java/seedu/address/model/person/Id.java, src/main/java/seedu/address/model/person/Medication.java, src/main/java/seedu/address/model/person/Person.java, src/main/java/seedu/address/model/person/Ward.java, src/main/java/seedu/address/model/util/SampleDataUtil.java, src/main/java/seedu/address/storage/JsonAdaptedPerson.java, src/main/java/seedu/address/ui/PersonCard.java, src/test/java/seedu/address/logic/LogicManagerTest.java, src/test/java/seedu/address/logic/commands/CommandTestUtil.java, src/test/java/seedu/address/logic/commands/EditCommandTest.java, src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java, src/test/java/seedu/address/logic/parser/AddCommandParserTest.java, src/test/java/seedu/address/logic/parser/EditCommandParserTest.java, src/test/java/seedu/address/model/person/PersonTest.java, src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java, src/test/java/seedu/address/storage/JsonAddressBookStorageTest.java, src/test/java/seedu/address/storage/JsonSerializableAddressBookTest.java, src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java, src/test/java/seedu/address/testutil/PersonBuilder.java, src/test/java/seedu/address/testutil/PersonUtil.java
Integrate patient into Person:
- Change constructor
- Add new methods
- Add new fields
Add new field classes with necessary methods and field:
- Id
- Ward
- Diagnosis
- Medication
=> Branch integratepatient

src/main/java/seedu/address/logic/Messages.java, src/main/java/seedu/address/logic/commands/EditCommand.java, src/main/java/seedu/address/logic/parser/AddCommandParser.java, src/main/java/seedu/address/logic/parser/EditCommandParser.java, src/main/java/seedu/address/logic/parser/ParserUtil.java, src/main/java/seedu/address/model/person/Medication.java, src/main/java/seedu/address/model/person/Person.java, src/main/java/seedu/address/model/util/SampleDataUtil.java, src/main/java/seedu/address/storage/JsonAdaptedPerson.java, src/test/data/JsonAddressBookStorageTest/invalidAndValidPersonAddressBook.json, src/test/data/JsonAddressBookStorageTest/invalidPersonAddressBook.json, src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json, src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json, src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json, src/test/java/seedu/address/logic/LogicManagerTest.java, src/test/java/seedu/address/logic/commands/AddCommandTest.java, src/test/java/seedu/address/logic/commands/CommandTestUtil.java, src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java, src/test/java/seedu/address/logic/parser/AddCommandParserTest.java, src/test/java/seedu/address/logic/parser/EditCommandParserTest.java, src/test/java/seedu/address/model/AddressBookTest.java, src/test/java/seedu/address/model/person/PersonTest.java, src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java, src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java, src/test/java/seedu/address/testutil/PersonBuilder.java, src/test/java/seedu/address/testutil/PersonUtil.java, src/test/java/seedu/address/testutil/TypicalPersons.java
Add a new medication field that takes in string 
Update test case to take into account new medication field
=> New Medication Field

src/main/java/seedu/address/commons/util/DateUtil.java, src/main/java/seedu/address/model/appointment/Appointment.java, src/test/java/seedu/address/model/appointment/AppointmentTest.java
Create an Appointment class that will be associated with a patient. It follows the dd-MM-yyyy-HH-mm date time format.
Having this Appointment class will allow us to add the functionality of keeping track of a patients appointment.
=> Create Appointment class

src/main/java/seedu/address/logic/commands/AddAppointmentCommand.java, src/main/java/seedu/address/logic/parser/AddAppointmentCommandParser.java, src/main/java/seedu/address/logic/parser/AddressBookParser.java, src/main/java/seedu/address/logic/parser/CliSyntax.java, src/main/java/seedu/address/logic/parser/ParserUtil.java, src/main/java/seedu/address/model/person/Person.java
Create AddAppointmentCommandParser class to parse arguments into new AddAppointmentCommand.
Create skeleton of AddAppointmentCommand class to add appointment details to patient.
This will ensure string fields parsed into the command has the correct format for appointment description, start date time, end date time and index.
=> Create add appointment command parser 

src/main/java/seedu/address/logic/parser/AddAppointmentCommandParser.java
Change implementation to use ArgumentMultiMap solely
The previous iteration used splitting of string which may cause issues if not carefully handled
=> Fix implementation of add appointment parser

src/main/java/seedu/address/logic/commands/DeleteAppointmentCommand.java, src/main/java/seedu/address/logic/parser/AddressBookParser.java, src/main/java/seedu/address/logic/parser/DeleteAppointmentCommandParser.java, src/test/java/seedu/address/logic/parser/DeleteAppointmentParserTest.java
Closes #89
- Added parser file
- Added parser test file
- Added DeleteAppointmentCommand skeleton
=> Add Parser for del_appt command

src/main/java/seedu/address/logic/Messages.java, src/main/java/seedu/address/logic/commands/AddAppointmentCommand.java, src/main/java/seedu/address/model/appointment/Appointment.java, src/main/java/seedu/address/ui/PersonCard.java, src/main/resources/view/DarkTheme.css, src/main/resources/view/PersonListCard.fxml
Closes #92 Closes #102 
This PR is currently a draft version and is not fully completed. It may be helpful for debugging purposes as the feature development proceed.
=> Update viewing of notes and appointment in patients

src/main/java/seedu/address/logic/commands/ScheduleAllCommand.java, src/main/java/seedu/address/model/Model.java, src/main/java/seedu/address/model/person/Person.java, src/test/java/seedu/address/logic/commands/CommandTestUtil.java, src/test/java/seedu/address/logic/commands/ScheduleAllCommandTest.java, src/test/java/seedu/address/model/person/PersonTest.java, src/test/java/seedu/address/testutil/PersonBuilder.java, src/test/java/seedu/address/testutil/TypicalPersons.java
In this PR, I have made the following changes
-Add logic for schedule all command
-Add test cases to schedule all command
-made changes to TypicalPersons.java and CommandTestUtil.java to support the above mentioned tests
=> Add logic for schedule_all

docs/UserGuide.md
Add documentaion for make_appt and schedule_all.
=> Update User Guide to sync with new commands

src/main/java/seedu/address/commons/util/DateUtil.java, src/main/java/seedu/address/logic/Messages.java, src/main/java/seedu/address/logic/commands/ScheduleAllCommand.java, src/main/java/seedu/address/logic/commands/ScheduleDateCommand.java, src/main/java/seedu/address/logic/parser/ScheduleDateCommandParser.java, src/main/java/seedu/address/model/Model.java, src/main/java/seedu/address/model/ModelManager.java, src/main/java/seedu/address/model/appointment/AppointmentContainsDatePredicate.java, src/test/java/seedu/address/logic/commands/AddCommandTest.java, src/test/java/seedu/address/logic/commands/CommandTestUtil.java, src/test/java/seedu/address/logic/commands/ScheduleAllCommandTest.java, src/test/java/seedu/address/logic/commands/ScheduleDateCommandTest.java, src/test/java/seedu/address/logic/parser/ScheduleDateCommandParserTest.java, src/test/java/seedu/address/model/ModelManagerTest.java, src/test/java/seedu/address/testutil/TypicalPersons.java
Implement logic for ScheduleDateCommand
Previously command had no logic.
Now it can display the schedule on a specified date.
Fix minor parsing in ScheduleDateParser.
Add test for ScheduleDateCommand
=>  Add logic for schedule_date 

build.gradle, src/main/java/seedu/address/model/person/Person.java, src/main/java/seedu/address/ui/AppointmentCard.java, src/main/java/seedu/address/ui/AppointmentListPanel.java, src/main/java/seedu/address/ui/MainWindow.java, src/main/java/seedu/address/ui/PersonCard.java, src/main/resources/view/AppointmentListCard.fxml, src/main/resources/view/AppointmentListPanel.fxml, src/main/resources/view/CommandBox.fxml, src/main/resources/view/DarkTheme.css, src/main/resources/view/MainWindow.fxml, src/main/resources/view/PersonListCard.fxml
Closes #114 
UI Update changes include:
- Adjustment of logo to top right corner
- Adding of Appointment lists
- Customized appointment cards
Further improvements to do:
- Display of "No patients/appointments to show" when lists are empty
- General aesthetics
=> Branch appointments UI

docs/diagrams/UiClassDiagram.puml
Add changes to ui class diagram to accommodate new AppointmentCard and AppointmentListPanel classes
=> Update ui class diagram

docs/DeveloperGuide.md, docs/diagrams/DeleteAppointmentSequenceDiagram.puml
Closes #136 
Add sequence diagram to illustrate the logic behind `del_appt` process
=> Add sequence diagram to DG

src/main/java/seedu/address/logic/commands/ScheduleDateCommand.java
Reduce complexity of schedule_date command
Command is now "scheduledate" from "schedule_date"
=> Simplify schedule date command

src/main/java/seedu/address/commons/util/DateUtil.java, src/main/java/seedu/address/logic/commands/ScheduleDateCommand.java, src/main/java/seedu/address/model/appointment/AppointmentContainsDatePredicate.java, src/main/java/seedu/address/ui/AppointmentCard.java, src/main/java/seedu/address/ui/PersonCard.java
Improve readability of date and datetime of appointment
Abstract method to parse date and datetime into more readable format
=> Update displayed appointment for readability

src/main/java/seedu/address/logic/parser/AddCommandParser.java
=> Bug Fix: Change medication field to be optional when adding patients

src/main/java/seedu/address/logic/commands/AddAppointmentCommand.java, src/main/java/seedu/address/model/appointment/Appointment.java
=> Edit Appointment:toString

src/main/java/seedu/address/model/person/Diagnosis.java, src/main/java/seedu/address/model/person/Name.java, src/test/java/seedu/address/logic/parser/ParserUtilTest.java, src/test/java/seedu/address/model/person/NameTest.java, src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
Names (particularly in singapore), can contain special characters such as (),/-@
Additionally, names should not contain numbers.
As such, I believe that the constraints should be altered to fit this.
Also added a 50 character limit to the field
=> Bug fix: Change name field constraints

docs/UserGuide.md, src/main/java/seedu/address/logic/commands/AddCommand.java, src/main/java/seedu/address/logic/commands/EditCommand.java, src/main/java/seedu/address/model/person/Person.java, src/main/java/seedu/address/model/person/Ward.java, src/test/java/seedu/address/logic/commands/CommandTestUtil.java, src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
Updated ward formatting to be less strict for wider adaption
=> Update ward format restrictions

src/main/java/seedu/address/logic/commands/AddAppointmentCommand.java, src/main/java/seedu/address/logic/commands/DeleteAppointmentCommand.java, src/main/java/seedu/address/logic/commands/ScheduleAllCommand.java, src/main/java/seedu/address/model/person/Id.java, src/main/java/seedu/address/model/person/Medication.java, src/main/java/seedu/address/model/person/Name.java
Changed validation regex to accept (), -, ,, /, @
Changed Syntax of delappts, scheduleall, makeappt 
Closes #151 
Closes #147
Closes #148 
Closes #149
=> Change validation regex for name condition and update command syntax

src/main/java/seedu/address/logic/Messages.java, src/main/java/seedu/address/logic/commands/AddCommand.java, src/main/java/seedu/address/logic/commands/EditCommand.java, src/main/java/seedu/address/model/person/Id.java, src/main/java/seedu/address/model/person/Person.java, src/main/java/seedu/address/model/person/Ward.java
Adding warning message when special characters appear in the Id field can enhance user experience in the event that it was unintended.
=> Add warning message if special characters in Id

src/main/java/seedu/address/model/person/Diagnosis.java, src/test/java/seedu/address/model/person/DiagnosisTest.java
=> Make diagnosis with empty string valid

src/test/java/seedu/address/model/person/MedicationTest.java
=> Add Medication Test Cases

src/test/java/seedu/address/logic/parser/AddCommandParserTest.java, src/test/java/seedu/address/testutil/PersonBuilder.java
=> Add tests for optional fields

src/main/java/seedu/address/logic/commands/AddNotesCommand.java, src/main/java/seedu/address/logic/parser/AddNotesCommandParser.java, src/main/java/seedu/address/logic/parser/ParserUtil.java, src/main/java/seedu/address/model/person/Notes.java, src/main/java/seedu/address/storage/JsonAdaptedPerson.java, src/test/java/seedu/address/logic/parser/AddNotesCommandParserTest.java
In this PR I've made the following additions
-add validation regex for notes (1 alphanumeric character and limit of 80 characters)
-made it such that the pn/ prefix is compulsory for addnotes
-made it such that after the pn/ prefix there must be a note specified, will throw a warning if otherwise
=> FIx addnotescommand

docs/diagrams/StorageClassDiagram.puml
Remove Json Storage and Add Json Appointment
=> Uml diagram branch

docs/UserGuide.md
UG is not updated with the enhanced find features, and is also missing some other key details.
=> Update UG to reflect new functionalities

src/main/java/seedu/address/MainApp.java, src/test/java/seedu/address/logic/commands/AddAppointmentCommandTest.java, src/test/java/seedu/address/logic/commands/CommandTestUtil.java
=> Add Appointment Command Test for overlapping Dates

docs/UserGuide.md
close #320 
close #318 
close #314
=> Fix typos and change references to address book to WardWatch

docs/DeveloperGuide.md
update Use Cases 1 to 9 in the DG.
TODO:
Continue updating the remaining use cases, as well as adding any other necessary use cases.
=> Update UC1 to UC9 in DG

docs/DeveloperGuide.md
=> Update Effort Appendix

docs/UserGuide.md
Add must not be greater than 2147483647 constraint
close #364
=> Update index constraints

docs/UserGuide.md, src/main/java/seedu/address/MainApp.java
=> Add overall final changes to UG

docs/DeveloperGuide.md, docs/diagrams/AddActivityDiagram.puml, docs/diagrams/FindSequenceDiagram.puml, docs/diagrams/ModelClassDiagram.puml, docs/diagrams/ParserClasses.puml
=> Finalise DG
